### ISSUE TITLE
Issue with Android P

### ISSUE THREAD

**Issue by chaurasiadilip** [CAAPIM/Android-MAS-SDK#296]
Hi,
I am using your API (ver-1.4.00) in my project. it is not working on Android P only.
getting Prompt with "Detected problems with API compatibility" warning message and also getting an exception

android.os.ServiceSpecificException: (code 7)
at android.os.Parcel.createException(Parcel.java:1956)
at android.os.Parcel.readException(Parcel.java:1910)
at android.os.Parcel.readException(Parcel.java:1860)
at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
at android.security.KeyStore.get(KeyStore.java:195)
at android.security.KeyStore.get(KeyStore.java:206)
at java.lang.reflect.Method.invoke(Native Method)
at com.ca.mas.core.security.KeyStoreAdapter.get(KeyStoreAdapter.java:120)
at com.ca.mas.core.storage.implementation.KeyStoreStorage.readData(KeyStoreStorage.java:175)
at com.ca.mas.core.storage.implementation.KeyStoreStorage.deleteData(KeyStoreStorage.java:410)
at com.ca.mas.core.datasource.KeystoreDataSource.remove(KeystoreDataSource.java:158)
at com.ca.mas.core.store.PrivateTokenStorage.clear(PrivateTokenStorage.java:102)
at com.ca.mas.core.conf.ConfigurationManager$ClientChangeListener.onUpdated(ConfigurationManager.java:418)
at com.ca.mas.core.conf.ConfigurationManager.activate(ConfigurationManager.java:170)
at com.ca.mas.core.MobileSsoFactory.getInstance(MobileSsoFactory.java:171)
at com.ca.mas.core.MobileSsoFactory.getInstance(MobileSsoFactory.java:88)
at com.ca.mas.foundation.MAS.start(MAS.java:233)
at com.digitaslbi.hastingsdirect.HDApplication.initCAGateway(HDApplication.java:61)
at com.digitaslbi.hastingsdirect.HDApplication.onCreate(HDApplication.java:43)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
at android.app.ActivityThread.access$1100(ActivityThread.java:199)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

i am testing on Pixel that have official android P.
please help to resolve this issue.

**Comment by witrisna** [comment]
Hi,

Upgrade to next Mobile SDK 1.8.00 version is required for supporting Android P.
We are working on the coming Mobile SDK 1.8.00, for now, you can use 1.8.00-pre-release1 for testing.
To upgrade to 1.8.00-pre-release1, simply update your build.gradle dependency as follow:

```json
implementation 'com.ca:mas-foundation:1.8.00-Pre-Release1'
```
Please let us know if you experience any upgrade issue, since you are using 1.4.00, you may want review the [ChangeLog](https://github.com/CAAPIM/Android-MAS-SDK/blob/Stable/ChangeLog.md) for the changes.

**Comment by chaurasiadilip** [comment]
Hi,
Actually i am using  MAS storage API (Ver-1.4.00).i try to upgrade 1.8.00-pre-release1.I get following error
"error: resource integer/request_permissions_get_account (aka com.hastingsdirect.mobile.internal:integer/request_permissions_get_account) not found.
Message{kind=ERROR, text=error: resource integer/request_permissions_get_account (aka com.hastingsdirect.mobile.internal:integer/request_permissions_get_account) not found., sources=[/Users/dilchour/Desktop/Dileep/Android Projects/Hastings/app/src/main/res/layout/widget_policy_excess_header.xml:22], original message=, tool name=Optional.of(AAPT)}"
 will i have to change "msso_config.json" for latest build and i am using build.gradle dependency 
              
                 implementation  'com.ca:mas 1.4.00'

what will i do for upgrading sdk.

**Comment by witrisna** [comment]
Sorry, we don't have official 1.8.00 documentation yet,  but I can provide information on setting up the SDK with Android P. For 1.8.00, the SDK use [Android AccountManager](https://developer.android.com/reference/android/accounts/AccountManager) to stores tokens and user data, you need to setup AccountManager in your App, and here the steps:

1.  Create an Account Authenticator file (e.g authenticator.xml) file under /res/xml directory, the account authenticator has the following content:
```xml
<account-authenticator xmlns:android="http://schemas.android.com/apk/res/android"		 
     android:accountType="<account_name>"
     android:icon="@drawable/<image_name>"
     android:smallIcon="@drawable/<image_name>"		 
     android:label="@string/<app_name>"/>
```
2. Add the folloing service to the Android manifest file:
```xml
<service
    android:name="com.ca.mas.core.storage.sharedstorage.MASAuthenticatorService"
    android:exported="false">
    <intent-filter>
        <action android:name="android.accounts.AccountAuthenticator" />
    </intent-filter>

    <meta-data
        android:name="account.name"
        android:resource="@string/<account_name>" />
    <meta-data
        android:name="android.accounts.AccountAuthenticator"
        android:resource="@xml/<account_authenticator_name>" />
</service>
```

For using the Storage API, you can use the following configuration:
```json
implementation 'com.ca:mas-foundation:1.8.00-pre-release1'
implementation 'com.ca:mas-storage:1.8.00-pre-release1'
```
using com.ca:mas is fine, however it will pull all other modules (e.g masui, connecta, ...) into your project,  which may increase the size of your application. 

From the information provided, looks like there is android.permission.GET_ACCOUNTS Permission, for Android P, android.permission.GET_ACCOUNTS is not required, however, if you still experience the issue try to add the  android.permission.GET_ACCOUNTS to your App:

```json
<uses-permission android:name="android.permission.GET_ACCOUNTS" tools:node="replace" />
```

**Comment by chaurasiadilip** [comment]
hi,
Thanks for quickly response.i have processed all things as provided .but showing error some classes  are missing . Missing class is "import com.ca.mas.core.http.MAGResponse;". Will i have to add any other API in project.

**Comment by chaurasiadilip** [comment]
Thank for replying . Now  it is working . is this SDK stable  or it is in testing phase .if not  stable , when will  get stable version.

**Comment by BobbyWeber** [comment]
Version 1.8.00 was released. Please use the official release version. Closing this Issue.

**Comment by chaurasiadilip** [comment]
Thanks for updating me
